/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <String.h>
/* Header for class com_quan_car_qmeeting_JniUtils */

#ifndef _Included_com_quan_car_qmeeting_JniUtils
#define _Included_com_quan_car_qmeeting_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quan_car_qmeeting_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_quan_car_qmeeting_JniUtils_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     com_quan_car_qmeeting_JniUtils
 * Method:    updateString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_quan_car_qmeeting_JniUtils_updateString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_quan_car_qmeeting_JniUtils
 * Method:    encodeFromC
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_quan_car_qmeeting_JniUtils_encodeFromC
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_quan_car_qmeeting_JniUtils
 * Method:    decodeFromC
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_quan_car_qmeeting_JniUtils_decodeFromC
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
